// <auto-generated />
using BookStore.ProjectionBuilder.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookStore.ProjectionBuilder.Postgres.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BookStore.ProjectionBuilder.Postgres.Database.Entities.BookStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("BookStores");
                });

            modelBuilder.Entity("BookStore.ProjectionBuilder.Postgres.Database.Entities.StreamVersion", b =>
                {
                    b.Property<string>("StreamName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<long>("Version");

                    b.HasKey("StreamName");

                    b.ToTable("StreamVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
