// <auto-generated />
using BookStore.ProjectionBuilder.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookStore.ProjectionBuilder.Postgres.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180315200737_AddStreamVersionsTable")]
    partial class AddStreamVersionsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BookStore.ProjectionBuilder.Postgres.Database.Entities.StreamVersion", b =>
                {
                    b.Property<string>("StreamName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<long>("Version");

                    b.HasKey("StreamName");

                    b.ToTable("StreamVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
